spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online-store
    username: postgres
    password: postgres
    jpa:
      show-sql: true
  liquibase:
    change-log: classpath:db/liquibase-changeLog.xml

